version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/dang-khoa-sport
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo

  admin:
    build: ./Admin
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - MONGO_URI=mongodb://mongo:27017/dang-khoa-sport
      - API_URL=http://backend:3000/api
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
